FROM postgres:12 as build
RUN apt-get update && apt-get install -y --no-install-recommends postgresql-server-dev-12 gcc make icu-devtools libicu-dev

RUN mkdir -p /root/parser
WORKDIR /root/parser
COPY pg_cjk_parser.c /root/parser/
COPY pg_cjk_parser.control /root/parser/
COPY Makefile /root/parser/
COPY pg_cjk_parser--0.0.1.sql /root/parser/
COPY zht2zhs.h /root/parser/
RUN make clean && make install

FROM postgres:12
COPY --from=build /root/parser/pg_cjk_parser.bc /usr/lib/postgresql/12/lib/bitcode
COPY --from=build /root/parser/pg_cjk_parser.so /usr/lib/postgresql/12/lib
COPY --from=build /root/parser/pg_cjk_parser--0.0.1.sql /usr/share/postgresql/12/extension
COPY --from=build /root/parser/pg_cjk_parser.control /usr/share/postgresql/12/extension
