
ARG POSTGRES_VERSION=16
FROM postgres:$POSTGRES_VERSION-alpine AS build
ARG POSTGRES_VERSION=16
RUN apk update && apk add musl-dev icu-dev make && \
    LLVM_VER=$(pg_config --configure | grep -oE "llvm[0-9]+" | head -1 | grep -oE "[0-9]+") && \
    apk add clang${LLVM_VER} llvm${LLVM_VER}-dev

RUN mkdir -p /root/parser
WORKDIR /root/parser
COPY pg_cjk_parser.c /root/parser/
COPY pg_cjk_parser.control /root/parser/
COPY Makefile /root/parser/
COPY pg_cjk_parser--0.0.1.sql /root/parser/
COPY pg_cjk_parser--0.0.1--0.1.0.sql /root/parser/
COPY pg_cjk_parser--0.1.0.sql /root/parser/
COPY zht2zhs.h /root/parser/
RUN make clean && make install

FROM postgres:$POSTGRES_VERSION-alpine
COPY --from=build /root/parser/pg_cjk_parser.bc /usr/local/lib/postgresql/bitcode
COPY --from=build /root/parser/pg_cjk_parser.so /usr/local/lib/postgresql/
COPY --from=build /root/parser/pg_cjk_parser--0.0.1.sql /usr/local/share/postgresql/extension/
COPY --from=build /root/parser/pg_cjk_parser--0.0.1--0.1.0.sql /usr/local/share/postgresql/extension/
COPY --from=build /root/parser/pg_cjk_parser--0.1.0.sql /usr/local/share/postgresql/extension/
COPY --from=build /root/parser/pg_cjk_parser.control /usr/local/share/postgresql/extension/
