name: Build pg_cjk_parser for postgres 12 and 16

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_pg12:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: false
          file: Dockerfile_pg12
          tags: postgres:12-dev
      -
        name: Run bash script to verify image postgres:12-dev
        run: pwd && ls -l && chmod +x ./postgres-12.sh && ./postgres-12.sh

  build_pg16:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: false
          file: Dockerfile_pg16
          tags: postgres:16-dev
      -
        name: Run bash script to verify image postgres:16-dev
        run: pwd && ls -l && chmod +x ./postgres-16.sh && ./postgres-16.sh

