name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: uninstall postgresql-14
      run: sudo apt-get remove -y postgresql-14 libpq-dev
    - name: configure
      run: sudo apt-get install -y postgresql-12 postgresql-server-dev-all gcc icu-devtools libicu-dev
    - name: debug
      run: ls -l /usr/include/postgresql && pg_config --pgxs && ls -l /usr/lib/postgresql
    - name: make
      run: make
    - name: make install
      run: make install
    
